export type InventoryPostingErrorCode =
  | 'CREDIT_CURRENCY_MISMATCH'
  | 'CREDIT_EXPOSURE_UNSTATED'
  | 'CREDIT_HOLD'
  | 'CREDIT_LIMIT_EXCEEDED'
  | 'FULFILLMENT_CUSTOMER_INELIGIBLE'
  | 'FULFILLMENT_ORDER_NOT_RELEASED'
  | 'FULFILLMENT_PROJECTION_DIVERGED'
  | 'FULFILLMENT_QUANTITY_OUT_OF_BOUNDS'
  | 'FULFILLMENT_RESERVATION_SHORTAGE'
  | 'FULFILLMENT_RESERVATION_STATE_CONFLICT'
  | 'FULFILLMENT_SHIPMENT_INVALID'
  | 'PAYABLES_AMOUNT_EXCEEDS_BALANCE'
  | 'PAYABLES_AMOUNT_INVALID'
  | 'PAYABLES_BILL_SETTLED'
  | 'PAYABLES_BILL_STATE_CONFLICT'
  | 'PAYABLES_DUPLICATE_SUPPLIER_INVOICE'
  | 'PAYABLES_LINE_UNPRICED'
  | 'PAYABLES_NOTHING_TO_BILL'
  | 'PAYABLES_ORDER_BILLED'
  | 'PAYABLES_ORDER_NOT_BILLABLE'
  | 'RECEIVABLES_AMOUNT_EXCEEDS_BALANCE'
  | 'RECEIVABLES_AMOUNT_INVALID'
  | 'RECEIVABLES_INVOICE_SETTLED'
  | 'RECEIVABLES_INVOICE_STATE_CONFLICT'
  | 'RECEIVABLES_LINE_UNPRICED'
  | 'RECEIVABLES_NOTHING_TO_INVOICE'
  | 'RECEIVABLES_ORDER_NOT_CONFIRMABLE'
  | 'RECEIVABLES_ORDER_NOT_INVOICEABLE'
  | 'RECEIVABLES_ORDER_NOT_REOPENABLE'
  | 'RECEIPT_ORDER_NOT_RELEASED'
  | 'RECEIPT_COST_REQUIRED'
  | 'RECEIPT_PROJECTION_DIVERGED'
  | 'RECEIPT_QUANTITY_OUT_OF_BOUNDS'
  | 'RECEIPT_CORRECTION_INVALID'
  | 'RECEIPT_FORWARD_DATE_REFUSED'
  | 'INVENTORY_ADJUSTMENT_APPROVAL_REQUIRED'
  | 'INVENTORY_ADJUSTMENT_REASON_REQUIRED'
  | 'INVENTORY_BACKDATE_LIMIT_EXCEEDED'
  | 'INVENTORY_BASE_UNIT_IMMUTABLE'
  | 'INVENTORY_COUNT_APPROVAL_REQUIRED'
  | 'INVENTORY_COUNT_COMPENSATION_CONFLICT'
  | 'INVENTORY_COUNT_EVIDENCE_CONFLICT'
  | 'INVENTORY_COUNT_REASON_REQUIRED'
  | 'INVENTORY_ITEM_INACTIVE'
  | 'INVENTORY_ITEM_UNIT_MISMATCH'
  | 'INVENTORY_LEGAL_ENTITY_INACTIVE'
  | 'INVENTORY_LOCATION_INACTIVE'
  | 'INVENTORY_PERIOD_CLOSED'
  | 'INVENTORY_POSTING_CAPABILITY_MISMATCH'
  | 'INVENTORY_POSTING_IDEMPOTENCY_CONFLICT'
  | 'INVENTORY_POSTING_INPUT_INVALID'
  | 'INVENTORY_POSTING_LOCK_TIMEOUT'
  | 'INVENTORY_POSTING_RELEASE_MISMATCH'
  | 'INVENTORY_POSTING_STORAGE_INVALID'
  | 'INVENTORY_POSTING_STORAGE_REJECTED'
  | 'INVENTORY_RECORDED_AT_REGRESSION'
  | 'INVENTORY_STOCK_NEGATIVE'
  | 'INVENTORY_TRANSFER_APPROVAL_REQUIRED'
  | 'INVENTORY_TRANSFER_REASON_REQUIRED'
  | 'INVENTORY_TRANSACTION_STATE_CONFLICT';

export class InventoryPostingError extends Error {
  override readonly name = 'InventoryPostingError';

  constructor(
    readonly code: InventoryPostingErrorCode,
    message: string,
    readonly details: Readonly<Record<string, string>> = Object.freeze({}),
  ) {
    super(`${code}: ${message}`);
  }
}
