export {
  ADOPTED_LANGUAGE_VERSION,
  ADOPTED_NORMALIZATION_PROFILE_VERSION,
  CANONICALIZATION_PROFILE_VERSION,
  CANONICAL_LANGUAGE_PROFILES,
  CONTENT_HASH_ALGORITHM,
  CONTENT_HASH_DOMAIN,
  DEFAULT_DISCLOSURE_TIER,
  DISCLOSURE_TIERS,
  IMMUTABLE_DEFAULTS_V0,
  LANGUAGE_VERSIONS,
  LEGACY_LANGUAGE_VERSION,
  LEGACY_NORMALIZATION_PROFILE_VERSION,
  LANGUAGE_VERSION,
  LATEST_LANGUAGE_VERSION,
  LATEST_NORMALIZATION_PROFILE_VERSION,
  NORMALIZATION_PROFILE_VERSIONS,
  NORMALIZATION_PROFILE_VERSION,
  PREVIOUS_LANGUAGE_VERSION,
  PREVIOUS_NORMALIZATION_PROFILE_VERSION,
  PROMOTE_STORAGE_CLASS_CAPABILITY_ID,
  QUERY_PARAMETER_LIMIT_V3,
  STATUS_ROLES,
  STRUCTURAL_LIMITS_V0,
  SUPPORTED_LANGUAGE_VERSIONS,
  SUPPORTED_NORMALIZATION_PROFILE_VERSIONS,
  SURFACE_ARCHETYPES,
  SURFACE_SLOTS,
  canonicalLanguageProfileFor,
  languageHasLegalEntityQueryScope,
  languageHasMaterializedStateFields,
  languageHasV3Features,
  type CanonicalLanguageProfile,
  type CanonicalLanguageVersion,
  type CanonicalNormalizationProfileVersion,
  type DisclosureTier,
} from './constants.js';
export {
  CanonicalModelError,
  type CanonicalDiagnostic,
} from './diagnostics.js';
export {
  QueryReadModelSchema,
  type QueryReadModel,
  SurfaceCompositionSchema,
  type SurfaceComposition,
  SurfaceWorkspaceSchema,
  type SurfaceWorkspace,
  SurfaceListSchema,
  type SurfaceList,
  SurfaceDocumentEditorSchema,
  type SurfaceDocumentEditor,
  type V6AuthoredApplicationPackage,
  type V6NormalizedApplicationPackage,
  AuthoredApplicationPackageSchema,
  CanonicalDecimalStringSchema,
  CanonicalSignedDecimalStringSchema,
  CanonicalIdSchema,
  CanonicalIntegerStringSchema,
  CanonicalReferenceSchema,
  CanonicalScalarSchema,
  FieldTypeSchema,
  NormalizedApplicationPackageSchema,
  PredicateExpressionSchema,
  VersionedPredicateExpressionSchema,
  VersionedCanonicalScalarSchema,
  VersionedAuthoredApplicationPackageSchema,
  VersionedNormalizedApplicationPackageSchema,
  type AuthoredApplicationPackage,
  type CanonicalId,
  type CanonicalScalar,
  type FieldType,
  type NormalizedApplicationPackage,
  type PredicateExpression,
  type PredicateExpressionV3,
  type QueryLegalEntityScope,
  type QueryParameterReference,
  type V3AuthoredApplicationPackage,
  type V3NormalizedApplicationPackage,
  type V4AuthoredApplicationPackage,
  type V4NormalizedApplicationPackage,
  type V5AuthoredApplicationPackage,
  type V5NormalizedApplicationPackage,
  type VersionedAuthoredApplicationPackage,
  type VersionedNormalizedApplicationPackage,
  type VersionedPredicateExpression,
} from './schemas.js';
export {
  canonicalAuthoredProjection,
  normalizeApplicationPackage,
  parseAuthoredApplicationPackageJson,
  parseNormalizedApplicationPackageJson,
  parseVersionedAuthoredApplicationPackageJson,
} from './normalize.js';
export {
  PREDICATE_KERNEL_RECEIPT_VERSION,
  PREDICATE_LOWERING_PLAN_VERSION,
  PARAMETERIZED_PREDICATE_LOWERING_PLAN_VERSION,
  PREDICATE_POSITION_PROFILES,
  PREDICATE_POSITION_PROFILE_VERSION,
  QUERY_AGGREGATE_LOWERING_PLAN_VERSION,
  admitPredicateForExecution,
  inspectPredicateForExecution,
  type LiteralTruePredicate,
  type PredicateBindingPosition,
  type PredicateComparisonResolution,
  type PredicateEvaluationOptions,
  type PredicateFalseDisposition,
  type PredicateKernelEntryPoint,
  type PredicateKernelReceipt,
  type PredicateCostClass,
  type PredicateLoweringNode,
  type PredicateLoweringPlan,
  type PredicateLoweringRowId,
  type PredicatePositionProfile,
  type ParameterizedPredicateLoweringNode,
  type ParameterizedPredicateLoweringPlan,
  type ParameterizedPredicateLoweringRowId,
  type QueryAggregateLoweringPlan,
  type QueryFilterLoweringPlan,
} from './predicate-kernel.js';
export {
  QUERY_AGGREGATE_CONTRACT_V1,
  QUERY_AGGREGATE_KERNEL_RECEIPT_VERSION,
  QUERY_AGGREGATE_PROFILE_VERSION,
  evaluateQueryAggregateSemantics,
  type QueryAggregateElement,
  type QueryAggregateEvaluationRequest,
  type QueryAggregateFieldContract,
  type QueryAggregateKernelReceipt,
} from './query-aggregate-kernel.js';
export {
  LEGAL_ENTITY_SCOPE_CONTRACT_V1,
  LEGAL_ENTITY_SCOPE_KERNEL_RECEIPT_VERSION,
  LEGAL_ENTITY_SCOPE_PROFILE_VERSION,
  evaluateLegalEntityScopeSelection,
  type LegalEntityScopeCardinality,
  type LegalEntityScopeSelectionReceipt,
  type LegalEntityScopeSelectionRequest,
} from './legal-entity-scope-kernel.js';
export {
  canonicalize,
  canonicalizeAndHash,
  type CanonicalizedContent,
} from './canonicalize.js';
export {
  UNICODE_CASE_FOLD_EXPANSIONS,
  UNICODE_CASE_FOLD_SIMPLE_SOURCES,
  UNICODE_CASE_FOLD_SIMPLE_TARGETS,
  UNICODE_CASE_FOLD_VERSION,
  unicodeCaseFold,
} from './unicode-case-fold.js';

export const platformContract = Object.freeze({
  authority: 'canonical-model',
  product: 'greenfield-north-star-erp',
});
